### ISSUE TITLE
一点小疑惑

### ISSUE THREAD

**Issue by JH90iOS** [LeoMobileDeveloper/Blogs#11]
有一点小疑惑，请教一下，我对这里使用双向链表有点小疑问，既然已经有字典可以用来保存双向链表中某个节点的位置，那为什么不直接用字典来保存这个订阅者呢？而只是保存订阅者的位置，然后再通过位置来操作双向链表，直接用字典不是更方便吗？时间复杂度也是一样的。

**Comment by LeoMobileDeveloper** [comment]
@JH90iOS  EventBus那篇文章么？

**Comment by LeoMobileDeveloper** [comment]
需要的是一个Key - Value Array的数据结构，字典只能存Key-Value的

**Comment by JH90iOS** [comment]
嗯，是这篇文章，我明白这里需要是一个Key - Value Array的数据结构，我看到在你的代码中使用了双向链表来实现这种 Value Array 的数据结构，不过我发现这个双向链表中每一个节点都有一个 uniqueId 作为唯一标识，而且在例如删除操作中，也是先根据这个 uniqueId 在字典中查找到这个结点然后进行双向链表的相关操作，我不明白的是为什么不直接 用字典的数据结构，因为每一个结点对应一个唯一标识，为什么不能是 key - Muti Dictionary ，而是 key - LinkList

**Comment by LeoMobileDeveloper** [comment]
@JH90iOS 主要的原因是想保证先subscribe的先收到通知，这样就需要一个有序的数据结构，所以没用字典。

**Comment by JH90iOS** [comment]
明白了，非常感谢！
