### ISSUE TITLE
文章勘误

### ISSUE THREAD

**Issue by liumenghua** [LeoMobileDeveloper/Blogs#16]
博主的文章写的很好，仔细阅读时发现一出语句问题：
《优雅的开发TableView》中：
“继承是一个实现代码复用的解决方案，通过在基类中实现-子类重写的方式进行服复用。”
结尾应该是多了一个“服”。

不算是一个问题，阅读时发现，顺手提一下～

**Comment by LeoMobileDeveloper** [comment]
改啦
