### ISSUE TITLE
Symbol地址不连续疑问🤔️

### ISSUE THREAD

**Issue by Yousanflics** [LeoMobileDeveloper/Blogs#2]
## 大佬你好我是一名大三的 iOS 懵新，今天看你博客中 iOS 编译过程的原理和应用 对 Symbol 中的这段代码有个疑问
```
# Symbols:
  地址     大小          文件编号    方法名
# Address	Size    	File       Name
0x1000021B0	0x00000109	[  2]     -[ULWBigResponseButton pointInside:withEvent:]
0x1000022C0	0x00000080	[  3]     -[ULWCategoryController liveAPI]
0x100002340	0x00000080	[  3]     -[ULWCategoryController categories]
....
```
0x1000021B0 加上 size 0x00000109 末地址为 0x1000022B9 但是下一个地址的起始并不是 0x1000022BA 所以可以知道这个地方的地址并不连续，我猜想这个地方的不连续是不是跟文件编号有关，是不是文件编号相同的地址就是连续的，我理解这样是因为编号相同就是在同一个文件当中，那么这个当中的方法可以连续在一起编译，而不同文件中的方法即文件编号不同则需要放在不连续的内存中，相当于划分了一个块？再猜想的话会不会是针对每一个文件有固定的这样位置的大小，然后用不完的话就放在那里然后跳过使用下一个文件专属的块？

**Comment by LeoMobileDeveloper** [comment]
不连续应该是中间几行被我删了
