### ISSUE TITLE
深入理解ARC.md 这章不准确的地方

### ISSUE THREAD

**Issue by PengXinabc** [LeoMobileDeveloper/Blogs#7]
关于深入理解ARC.md 这章的理解其中关于autoreleasepool有一点是不对的吧
__weak NSObject * obj;
@autoreleasepool {
    NSObject * temp = [[NSObject alloc] init];
    obj = temp;
}
这段代码是不会加入pool的，通过alloc创建的自己会管理不会放入pool。释放是因为超过作用域自然会释放局部变量。
可以这么写NSObject * temp = [NSObject creatObj];在MRC下是肯定加入pool，但是在ARC下这块通过tls存储进行了优化省去了发送autorelease和retain操作，并不一定加入pool。

**Comment by LeoMobileDeveloper** [comment]
@PengXinabc 内容确实有问题，回头找个时间改下，多谢指正
